### ISSUE TITLE
SpaceJam

### ISSUE THREAD

**Issue by clearloop** [davxy/jam-conformance#13]
## SpaceJam Fuzzing

| release | date | description |
| - | - | - |
| [all][all] | . | The releases page of spacejam binaries |
| [0.6.7][latest]  | 2025-08-13 | the latest spacejam release matched v0.6.7 |

for shortcut of downloading the latest `spacejam` binary  (`2025-08-13`)

```bash
curl -fsSL https://sh.spacejam.dev | sh
```

### Usage

```bash
# running a fuzz target
spacejam fuzz target -v 

# running a fuzzer
spacejam fuzz fuzzer -t jam-test-vectors/traces/storage -v

# running a single trace
spacejam fuzz tx trace.json -v
```

Note that `RUST_LOG` is available, feel free to request new logs for `spacejam` which helps debugging !

### Known Issues

- [ ] invocations out of storage and preimages are not tested

[latest]: https://github.com/spacejamapp/specjam/releases/tag/0.6.7
[all]: https://github.com/spacejamapp/specjam/releases

**Comment by clearloop** [comment]
sorry for breaking in [#11](https://github.com/davxy/jam-conformance/issues/11#issuecomment-3175962034)!

I was testing our fuzzer format with duna's target and then tried their reports then commented on the issue unconsciously )), I'm trying others' reports first bcz I want to confirm if our binary is ready enough!

however I'm still stuck at [duna_04](https://github.com/spacejamapp/jam-test-vectors/blob/main/traces/fuzz/duna_04.json), the source seems got removed, which has empty pending reports in pre-state but have assurances trying to integrate to the specified core

**Comment by davxy** [comment]
> sorry for breaking in https://github.com/davxy/jam-conformance/issues/11#issuecomment-3175962034! I was testing our fuzzer format with duna's target and tried their reports then commented on the issue unconsciously, I'm trying others' reports since I want to confirm if our binary is ready enough first

No problem

I tried running your target and encountered a failure on your side, apparently related to the order of the assurances, which should be sorted by val index.

```log
❯ ./spacejam fuzz target -vvv
2025-08-13 13:03:12  INFO spacejam::fuzz::target: Listening on "/tmp/jam_target.sock"
2025-08-13 13:03:18 DEBUG  read: spacejam::fuzz: message(length): Info
2025-08-13 13:03:18 DEBUG write: spacejam::fuzz: message(16): Info
2025-08-13 13:03:18 DEBUG  read: spacejam::fuzz: message(length): SetState(len=21)
2025-08-13 13:03:18 DEBUG write: spacejam::fuzz: message(33): StateRoot(0xc2d2a5bf305862ae66218e62bf8d1398388850b95bf62b0c9d30269583399dec)
2025-08-13 13:03:18 DEBUG  read: spacejam::fuzz: message(length): ImportBlock(slot=1, hash=0x8a2c121136c29f2bf588a9f29aad83ba0fb3f64f5e8475e933617bb8591875b7)
2025-08-13 13:03:18 DEBUG write: spacejam::fuzz: message(33): StateRoot(0x5692d3a3929e0e8390e80dcfa838e95f26f72b7f4accd65fa57c1ed6a1e7a9cb)
2025-08-13 13:03:18 DEBUG  read: spacejam::fuzz: message(length): ImportBlock(slot=2, hash=0x3f3fd732f6ba3bee0f533fc13575a0071ed14685bcaa6c18dc9cb65c2e0be050)
2025-08-13 13:03:18 ERROR spacejam::cmd: NotSortedOrUniqueAssurers
```

As a side note, if the block you receive is invalid - which is *not* the case for `0x3f3fd732f6ba3bee0f533fc13575a0071ed14685bcaa6c18dc9cb65c2e0be050`
but could happen if the fuzzer intentionally sends an incorrect mutation to check behavior  - you should
not terminate the target. Instead, simply wait for the next block (which should have the same parent of the incorrect one).

Here is the trace for you to reproduce: https://github.com/davxy/jam-conformance/tree/main/fuzz-reports/spacejam/1755083543

**Comment by clearloop** [comment]
We just released [SpaceJam 0.6.7-pre.2](https://github.com/spacejamapp/specjam/releases/tag/0.6.7-pre.2) with fixes, however, I'm current stuck at some reports from others without any clues to push forward and think some of the traces may not correct

### 1. Privileges mismatched, host call `bless` from [zig-10][zig-10]


```
...

DEBUG program: Decoded instruction: Bless { manager: 0, assign: 0, designate: 324788131, auto_acc: [] } target="boot"

...

ERROR keyval mismatch: Privileges: 0x0c000000000000000000000000000000000000000000000000000000000000
DEBUG polkajam: Privileges { bless: 0, designate: 0, assign: [0, 324788131], always_acc: {} }
DEBUG spacejam: Privileges { bless: 0, designate: 324788131, assign: [0, 0], always_acc: {} }

...
```

SpaceJam correctly applied the decoded bess instruction however the result in polkajam got some offset

### 2. Guarantee signature verification failed from [duna-05][duna-05]


The report is at the same slot as the block, however using current validators from pre-state can not verify the guarantee signatures


### 3. Anchor not found in [duna-13][duna-13]

```
WARN stf:guarantee: could not find anchor: 0xafa99c54ceb9faed804f2588799d2dd1478d38f4ab886e11038ad17bb87b3b30 
in recent blocks: [
    "a0ba66552ef349e11f59516ce2403600d51ed57609025eaaaba0310be38f3660",
    "a6d54c21ebe42bd3e853e4d7a4a5367b1c1fe9f6f4fb9bdcfdc195a4e9b7e73e",
    "7bd3aa3cc4a2bbe54a8fdd6ff7e01fee5a834ac1041b6631af793a5cbf853025",
    "1bf21a446ae050f186d1a798bc793b5566e7db49c295474ef2c36b162ab98fd3",
    "852ce8dd7fb08e7444977b13e0871f095d3a6823c164938283c8a0f0881444ba",
    "b92d25a44148552292568e66752f4c8b0e998f278572c1dcf470585ea7bf9b69",    
    "f5a2b1433c42393c0cc57a4d4b1f51a34e31fb46db8f15f34675a31559e1cc69", 
    "a66a09accb090b3d6c9a3835a1f0c887015466c9c1f9bda40b729093135268a6"
]
```

The anchor is indeed not exists ...

### 4. Code hash not matched from [java-15][java-15]

```
DEBUG stf:accumulate: upgrade account 757125586, code=0x0000000000000000000000000000000000000000000000000000000000000000, previous=0x11790679b74be6b7ce5b43cc3569e1d2ecca7fabe4b28db0595c76ef084c226c
    DEBUG stf:accumulate: PVM execution continued for service 757125586, reason: Halt
    TRACE stf: handle block history
     WARN stf:guarantee: bad code hash for service 564523456: 0x0000000000000000000000000000000000000000000000000000000000000000 != 0x11790679b74be6b7ce5b43cc3569e1d2ecca7fabe4b28db0595c76ef084c226c
```
code hash updated for `757125586` while `` expected to have the previous code hash of `757125586`, we just fixed similar tests from duna's reports, so feeling weird that we failed on this


### Others

1. dependency missing in [java-27][java-27], investigating atm ...



[duna-05]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/jamduna/fixed/1754982087/00000005.json
[duna-13]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/jamduna/jam-duna-target-v0.13-0.6.7_gp-0.6.7/1755150526/00000013.json
[java-15]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/javajam/1755155383/00000015.json
[java-27]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/javajam/1755155137/00000027.json
[zig-10]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/jamzig/jamzig-target-0.1.0_gp-0.6.7/fixed/1754988078/00000010.json

**Comment by davxy** [comment]
New report for you: https://github.com/davxy/jam-conformance/tree/main/fuzz-reports/spacejam/1755183715

> so if failing on importing blocks, shall I return the state root anyway?

Yes. Always **return the state root of the last successfully imported block**. Some blocks will be intentionally invalid; in those cases, returning the previous state root implicitly signals that the block was not imported, and you then wait for the next block. In short, the protocol is the same as for a successful import, except you return the previous state root instead of a new one.

> btw if it is possible sharing some insights on my https://github.com/davxy/jam-conformance/issues/13#issuecomment-3187497189, for 1. I have been stuck in it for two days, a PVM trace will be super helpful!

I'll have a look

**Comment by clearloop** [comment]
just released [spacejamapp/specjam@0.6.7-pre.5](https://github.com/spacejamapp/specjam/releases/tag/0.6.7-pre-5) which removed the extra gas charging raised by pvm tests

**Comment by clearloop** [comment]
SpaceJam binaries for 0.7.0  [spacejamapp/specjam@0.7.0](https://github.com/spacejamapp/specjam/releases/tag/0.7.0)

**Comment by clearloop** [comment]
[spacejamapp/specjam@0.7.0-pre.3](https://github.com/spacejamapp/specjam/releases/tag/0.7.0-pre.3) 2x-5x optimized in runtime logic 🚀

**Comment by clearloop** [comment]
[spacejam@0.7.0-pre.6](https://github.com/spacejamapp/specjam/releases/tag/0.7.0-pre.6)

oh sorry, I didn't maintain a chain in my fuzzer so sort of cache got invalid, just did some workaround for adapting linear block importing for patching new epoch in safrole, it works for all of the safrole tests and the current fuzz tests now

the case I'm not handling in the fuzzer target atm is that missing sort of blocks on the finalized chain that I don't have enough tickets to re-calculate the ticket mark, but likely we will not have this case in current fuzz protocol, bcz it requires us routing to the missing blocks from the fuzzer?

**Comment by davxy** [comment]
Your target now only works when I run outside of a docker container? 
For various reasons I run targets on docker

```sh
❯ ./target.py run --docker spacejam
Action: run, Target: spacejam, OS: linux
Running spacejam on docker image debian:stable-slim (command ./spacejam fuzz target /tmp/jam_target.sock)
Waiting for target termination (pid=297686)

thread 'tokio-runtime-worker' panicked at /Users/clearloop/code/spacejam/crates/pvm/spacevm/src/lib.rs:95:10:
fix me later: Permission denied (os error 13)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tokio-runtime-worker' panicked at /Users/clearloop/code/spacejam/crates/pvm/spacevm/src/lib.rs:95:10:
fix me later: Permission denied (os error 13)

thread 'tokio-runtime-worker' panicked at /Users/clearloop/code/spacejam/crates/pvm/spacevm/src/lib.rs:95:10:
fix me later: Permission denied (os error 13)
```

**Comment by davxy** [comment]
Fixed: https://github.com/davxy/jam-conformance/commit/7bc92183d2745ab2fde9791e5bbcbbaa5e11c968

Was sufficient to set HOME env var

**Comment by clearloop** [comment]
> If I execute 1756572122 first it passes, but if I execute all the other sessions in the folders that come first (in order) then it always fail.

just updated the binaries at [spacejam-0.7.0.pre.9](https://github.com/spacejamapp/specjam/releases/tag/0.7.0-pre.9)

likely mainly caused by sort of race in cache since sometimes `1756572122` works and sometimes not, however I failed to reproduce the case with both my linux/macos machines, don't want to waste more time on this, so we now clean all cache on each new session > <

if it is possible to update our reports of the old failures (if they still fail) btw in the next batch? I believe the error messages may help a lot as well

**Comment by davxy** [comment]
I updated the reports table and your report files that are still failing

**Comment by clearloop** [comment]
there are 3 cases I'm investigating now, especially [1763371498](https://github.com/davxy/jam-conformance/discussions/117), I think the designate and the bless services could be messed up in the trace generator

it could be related with the problem I'm struggling with today `1761654684` as well (I saw this is removed from my table, but it is actually still failing in my local env...), drawn validators got updated but the trace expects not, which can be explained by this as well

for `1763371127` and `1763371379`, would be helpful if there are `report.json` for the reason of failure imports

**Comment by clearloop** [comment]
1. aligned to [Standard Target Packaging](https://github.com/davxy/jam-conformance/blob/main/fuzz-proto/README.md#standard-target-packaging), the image is `clearloop/spacejam:latest`, current at version `0.1.1`
2. the [summary-table][st] says our pass is `264/336`, however for a local processing, I got `328/336`, fixed the rest 8 tests and made it `336/336` with the docker image locally, worth more investigations if remote is still buggy


[st]: https://github.com/davxy/jam-conformance/blob/main/fuzz-reports/0.7.2/summaries/summary-table.md
